### ISSUE TITLE
注册之后未能实现自动登录

### ISSUE THREAD

**Issue by coolbit-in** [coolbit-in/bookseller#1]
需要修改 register view

**Comment by kokdemo** [comment]
你看能不能直接跳转到一个登陆页面，帮他们预填信息，然后登陆

**Comment by coolbit-in** [comment]
我已经在最新的提交中改好了，注册成功后自动登录

2014-04-15 17:06 GMT+08:00 kok liu notifications@github.com:

**Comment by kokdemo** [comment]
没看到你已经close了……话说那个站内信……
